scrape_configs:
  - job_name: 'main'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:7999']

  - job_name: 'simple'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:8000']

  - job_name: 'web_server'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:8001']
      - targets: ['localhost:8002']

